# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

$(FLOAT_OBJ): $(FLOAT_SRC)
	$(call make_command, $(CC), -c, cc -E $(FLOAT_SRC), $(FLOAT_SRC))
